Update Performance

diff --git a/Performance b/Performance
--- a/Performance
+++ b/Performance
@@ -1,27 +1,28 @@
 Performance.sh
 #! /bin/bash
-set -x
-## to ensure root user 
-if [! "$UID" -ne 0]; then
-echo " must be root to execute this cript" || exit (0)
-Else do: 
-# create function to check computer performance
-Function watch_ps {
-declare -a watch = (ps watch -ac --format pid && %cpu)
-for pid, %cpu in $watch enumerate($watch) 2> /dev/null > watch_ps.txt
-  
+Declare Global:
+ { Chronilize = ( ps && watch -ac | less -nr 10 --format pid && %cpu)
+   Dailylog = 'Datime(time) %d ":" %d ":" %d ":" %d % (format %month %year %day %hours)'
+ }
+ set -x
+If [ "$UID" -ne 0]: 
+  Echo " must be root to execute this cript" || exit (0)
+Fi:
 set -0 errtrace
-Err declare: "there's an error from the previous excuted fg command" #?
-return $watch_ps
+Perform () {
+  For logging in ${Chronilize}: | less && tail -n 20 {print $1 ":" $2 ":" $3} > $Dailylog(logger.txt)
+   do Err declare: Echo " if there's an error from foreground command:" 
+     exec > 2 & $Dailylog(Perform_error.txt)
+  done
+return $Perform.Dailylog()
 }
-done 
 
 Function sys_log {
-Declare -a var = ./var/log/sys.log
-if [! -f "$var"] then;
-Echo "the log is empty"
-else do:
-for -f in $var
-fm type -f {ctime, atime, mtime} | less wc sys_log.txt
-done
+  Declare -a var = ./var/log/sys.log
+  if [! -f "$var"] then;
+    Echo "the log is empty"
+  else do:
+    for -f in $var
+    fm type -f {ctime, atime, mtime} | less wc sys_log.txt
+  done
 }
